const productsList = [
  {
    id: "1",
    title: "WH-CH520 Wireless",
    desc: "With up to 50-hour battery life and quick charging, you’ll have enough power for multi-day road trips and long festival weekends.",
    img: "https://m.media-amazon.com/images/I/41lArSiD5hL._AC_SX679_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/811UeUfPYdL._AC_SY450_.jpg",
      "https://m.media-amazon.com/images/I/91tTIC0vQML._AC_SY450_.jpg",
      "https://m.media-amazon.com/images/I/81gqmwsufOL._AC_SY450_.jpg",
      "https://m.media-amazon.com/images/I/41bqlx+PPzL._AC_SX450_.jpg",
    ],
    colors: ["Black"],
    price: 38,
    oldprice: 45,
    type: "offers",
    category: "accessories",
    brand: "Sony",
    rating: 4.5,
  },
  {
    id: "2",
    title: "CL750 Wired",
    desc: "🎧 HIGH-QUALITY SOUND – Artix headphones wired provide an immersive audio experience with crisp, clear, and dynamic sound, balanced sound signature, and rich bass thanks to the 40mm drivers. Soft ear cushions block out ambient noise, so you can focus on your music or audio. The wired connection provides reliable and consistent sound quality, regardless of the device you are using. The built-in microphone allows you to take hands-free calls. Back to School Supplies Gift for Boys & Girls College.",
    img: "https://m.media-amazon.com/images/I/817HZoT0brL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/81qKVPm5-0L._AC_SY450_.jpg",
      "https://m.media-amazon.com/images/I/81M-cJMvwpL._AC_SY450_.jpg",
      "https://m.media-amazon.com/images/I/71OnALp+ZoL._AC_SY450_.jpg",
      "https://m.media-amazon.com/images/I/81nLBc6+2NL._AC_SX450_.jpg",
    ],
    colors: ["Turquoise"],
    price: 32,
    oldprice: 40,
    type: "",
    category: "accessories",
    brand: "Artix",
    rating: 4.4,
  },
  {
    id: "3",
    title: " 5.3 Wireless Earbuds",
    desc: "【Bluetooth 5.3 & One-Step Pairing】Featuring the most advanced Bluetooth 5.3 technology, MOZOTER Wireless Earbuds support HSP HFP A2DP AVRCP, which provides stable transmission speed and instant pairing without interruptions. These loud sound wireless earbuds will automatically turn on and enter pairing status when you open the charging case's lid, and you can pair the earbuds in Bluetooth settings of your phone.",
    img: "https://m.media-amazon.com/images/I/71CxZ653JNL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/71zUq7FmbiL._AC_SY450_.jpg",
      "https://m.media-amazon.com/images/I/71M0I1BoKoL._AC_SY450_.jpg",
      "https://m.media-amazon.com/images/I/71sZ7kWDPJL._AC_SY450_.jpg",
      "https://m.media-amazon.com/images/I/71ZvehbKbWL._AC_SY450_.jpg",
    ],
    colors: ["Black"],
    price: 18,
    oldprice: 22,
    type: "trending",
    category: "accessories",
    brand: "MOZOTER",
    rating: 4.3,
  },
  {
    id: "4",
    title: "Fast Charger Block Wall",
    desc: "C Type Charger Fast Charge: Upgraded usb c cable support QC 2.0/3.0 fast charge technology.Sync and Charge simultaneously at fast speeds on your USB Type C compatible devices.",
    img: "https://m.media-amazon.com/images/I/71eggbEbHXL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/61o7bYM8MUL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61W8l5PmQOL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/61zb8VGY4iL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81P1TkOKRFL._AC_SX679_.jpg",
    ],
    colors: ["Blue"],
    price: 12,
    oldprice: 15,
    type: "topseller",
    category: "accessories",
    brand: "Type C ",
    rating: 4.5,
  },
  {
    id: "5",
    title: "Laptop Skin Sticker",
    desc: "100% Brand New and High Quality. High resolution print, durable, dustproof, waterproof, non-fading reusable laptop skin stickers. The flexible film helps protect the laptop surface from scratches, abrasions and stains.",
    img: "https://m.media-amazon.com/images/I/71VivYDvjDL.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/71muVLrRyNL._AC_SX569_.jpg",
      "https://m.media-amazon.com/images/I/71j5ru5eoAL._AC_SX569_.jpg",
      "https://m.media-amazon.com/images/I/715dmViWygL._AC_SX569_.jpg",
      "https://m.media-amazon.com/images/I/81H0YfHHykL._AC_SX569_.jpg",
    ],
    colors: ["Flowers Plants"],
    price: 15,
    oldprice: 22,
    type: "trending",
    category: "accessories",
    brand: "AIMSA",
    rating: 3.9,
  },
  {
    id: "6",
    title: "Anker Portable Charger",
    desc: "Ultra-High Cell Capacity: The massive 20,000mAh cell capacity provides more than 5 charges for iPhone XS, almost 5 full charges for Samsung Galaxy S10, more than 4 charges for iPhone 11, and over 2 and a half charges for iPad mini 5.",
    img: "https://m.media-amazon.com/images/I/71s9NDno3FL._AC_SX679_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/41IisMZ+BjL._AC_.jpg",
      "https://m.media-amazon.com/images/I/41hrY931wZL._AC_.jpg",
      "https://m.media-amazon.com/images/I/51tmvGC5a6L._AC_.jpg",
      "https://m.media-amazon.com/images/I/61GSt9nZheL._AC_.jpg",
    ],
    colors: ["Black"],
    price: 24.3,
    oldprice: 35.0,
    type: "",
    category: "accessories",
    brand: "Anker",
    rating: 4.9,
  },
  {
    id: "7",
    title: "Selfie Stick Tripod",
    desc: "The ATUMTEK Selfie Stick and tripod stand are integrated, combined with a premium aluminum extendable stick, making the selfie stick exceptionally stable. The extendable pole is constructed with aviation-grade aluminum alloy and undergoes surface anodic oxidation for sturdiness and durability.",
    img: "https://m.media-amazon.com/images/I/61S1m4us80L._AC_SX466_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/61qxbCOmLVL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/61KsEKccOBL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/716nT8UrpsL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/611Nhc43fRL._AC_SX466_.jpg",
    ],
    colors: ["Black", "Blue", "Red", "White"],
    price: 23.99,
    oldprice: 39.99,
    type: "",
    category: "accessories",
    brand: "ATUMTEK",
    rating: 4.2,
  },
  {
    id: "8",
    title: "Ytonet Laptop Case",
    desc: "This laptop sleeve dimensions: 15.7 x 11.2 x 2 inch (L x W x H); The laptop compartment dimensions: 14.6 x 10.6 x 1.6 inch (L x W x H); One compartment for 15.6 inch laptop, the additional mesh pocket storage space keeps the items well-organized, such as your pens, cables, mouse, earphone, mobile phones, iPad or laptop accessories. Constructed with a modern slim and lightweight design to accommodate daily use and protection needs",
    img: "https://m.media-amazon.com/images/I/81On3MEFDRL._AC_SX466_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/51VfmButMYL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/81vmrRsD3XL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/71YrgNaQrOL._AC_SX466_.jpg",
      "https://m.media-amazon.com/images/I/71n7gMvkzkL._AC_SX466_.jpg",
    ],
    colors: ["Black", "Coral pink", "Dark blue", "Floral Rose"],
    price: 22.12,
    oldprice: 27.5,
    type: "",
    category: "accessories",
    brand: "Ytonet",
    rating: 4.1,
  },
  {
    id: "9",
    title: "Tablet Stand Adjustable",
    desc: "This tablet stand applies to 4 - 13 inch tablet and phone, such as new 2022/ 2021 iPad Pro 11/ 12.9 inch, iPad 10.9, iPad Air 5, iPad mini 6, iPad Pro 9.7 / 10.5, Surface Pro, Galaxy Tab, iPhone 14 Pro Max, iPhone 13 Pro Max, iPhone 12, iPhone 11. If you use a tablet larger than 12” and found it’s not stable to use, you can set it horizontally, which helps maintain more stability.",
    img: "https://m.media-amazon.com/images/I/71YnvIEkWwL._AC_SY879_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/714-diW-HYL._AC_SY879_.jpg",
      "https://m.media-amazon.com/images/I/61XKjUOWFpL._AC_SY879_.jpg",
      "https://m.media-amazon.com/images/I/61Iau+z9PHL._AC_SY879_.jpg",
      "https://m.media-amazon.com/images/I/71QnC1UnMHL._AC_SY879_.jpg",
    ],
    colors: ["Blue"],
    price: 10.99,
    oldprice: 19.99,
    type: "",
    category: "accessories",
    brand: "Lamicall",
    rating: 4.3,
  },
  {
    id: "10",
    title: "Apple Watch Band",
    desc: "Epuly magnetic clasp stainless steel mesh Loop fully compatible with apple watch band ultra 49mm 45mm 44mm 42mm series 8 (2022), series 7, series SE, series 6, series 5, series 4, series 3, series 2. Fits 6.10-7.3 inch wrist (155mm-185mm).",
    img: "https://m.media-amazon.com/images/I/81PGSHf8pnL._AC_SX679_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/81uCi0VT8yL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/810cOyjAr8L._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/81WyHT64xPL._AC_SX679_.jpg",
      "https://m.media-amazon.com/images/I/71lVmBOp7EL._AC_SX679_.jpg",
    ],
    colors: ["Black", "Gold", "Rose Gold"],
    price: 5.99,
    oldprice: 10.5,
    type: "offers",
    category: "accessories",
    brand: "Epuly",
    rating: 3.9,
  },
  {
    id: "11",
    title: "iPhone 14 Pro Max",
    img: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-14-pro-max-1.jpg",
    carouselImages: [
      "https://fdn.gsmarena.com/imgroot/reviews/22/apple-iphone-14-pro-max/lifestyle/-1024w2/gsmarena_004.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/22/apple-iphone-14-pro-max/lifestyle/-1024w2/gsmarena_005.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/22/apple-iphone-14-pro-max/lifestyle/-1024w2/gsmarena_007.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/22/apple-iphone-14-pro-max/lifestyle/-1024w2/gsmarena_013.jpg",
    ],
    desc: "Released 2022, September 16, 240g, 7.9mm thickness, iOS 16, up to iOS 16.6, 128GB/256GB/1TB storage, no card slot",
    colors: ["Deep Purple"],
    price: 1000,
    oldprice: 1250,
    type: "",
    category: "mobile",
    brand: "Apple",
    rating: 6.7,
  },
  {
    id: "12",
    title: "iPhone 13 Pro Max",
    img: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-pro-max-01.jpg",
    carouselImages: [
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-pro-max-3.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-pro-max-4.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/21/apple-iphone-13-pro-max/lifestyle/-1024w2/gsmarena_003.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/21/apple-iphone-13-pro-max/lifestyle/-1024w2/gsmarena_002.jpg",
    ],
    desc: "Released 2021, September 24, 240g, 7.7mm thickness, iOS 15, up to iOS 16.6, 128GB/256GB/1TB storage, no card slot",
    colors: ["Alpine Green"],
    price: 883,
    oldprice: 999,
    type: "trending",
    category: "mobile",
    brand: "Apple",
    rating: 5.6,
  },
  {
    id: "13",
    title: "Galaxy Z Flip5",
    img: "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-z-flip5-5g-r1.jpg",
    carouselImages: [
      "https://fdn.gsmarena.com/imgroot/reviews/23/samsung-galaxy-z-flip5/lifestyle/-1024w2/gsmarena_001.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/23/samsung-galaxy-z-flip5/lifestyle/-1024w2/gsmarena_004.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/23/samsung-galaxy-z-flip5/lifestyle/-1024w2/gsmarena_006.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/23/samsung-galaxy-z-flip5/lifestyle/-1024w2/gsmarena_009.jpg",
    ],
    desc: "Released 2023, August 11, 187g, 6.9mm thickness, Android 13, One UI 5.1.1, 256GB/512GB storage, no card slot",
    colors: ["Green"],
    price: 850,
    oldprice: 989,
    type: "trending",
    category: "mobile",
    brand: "Samsung ",
    rating: 6.6,
  },
  {
    id: "14",
    title: "Galaxy S23 Ultra",
    img: "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s23-ultra-5g-1.jpg",
    carouselImages: [
      "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s23-ultra-5g-4.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/23/samsung-galaxy-s23-ultra/lifestyle/-1024w2/gsmarena_012.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/23/samsung-galaxy-s23-ultra/lifestyle/-1024w2/gsmarena_011.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/23/samsung-galaxy-s23-ultra/lifestyle/-1024w2/gsmarena_008.jpg",
    ],
    desc: "Released 2023, February 17, 234g, 8.9mm thickness, Android 13, One UI 5.1, 256GB/512GB/1TB storage, no card slot",
    colors: ["black"],
    price: 875,
    oldprice: 999,
    type: "",
    category: "mobile",
    brand: "Samsung ",
    rating: 7.8,
  },
  {
    id: "15",
    title: "Pixel 7 Pro",
    img: "https://fdn2.gsmarena.com/vv/pics/google/google-pixel7-pro-2.jpg",
    carouselImages: [
      "https://fdn.gsmarena.com/imgroot/reviews/22/google-pixel-7-pro/lifestyle/-1024w2/gsmarena_004.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/22/google-pixel-7-pro/lifestyle/-1024w2/gsmarena_007.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/22/google-pixel-7-pro/lifestyle/-1024w2/gsmarena_010.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/22/google-pixel-7-pro/lifestyle/-1024w2/gsmarena_015.jpg",
    ],
    desc: "Released 2022, October 13, 212g, 8.9mm thickness, Android 13, 128GB/256GB/512GB storage, no card slot",
    colors: ["Obsidian"],
    price: 800,
    oldprice: 878,
    type: "topseller",
    category: "mobile",
    brand: "Google",
    rating: 10,
  },
  {
    id: "16",
    title: "Pixel 6a",
    img: "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-6a-0.jpg",
    carouselImages: [
      "https://fdn.gsmarena.com/imgroot/reviews/22/google-pixel-6a/lifestyle/-1024w2/gsmarena_004.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/22/google-pixel-6a/lifestyle/-1024w2/gsmarena_005.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/22/google-pixel-6a/lifestyle/-1024w2/gsmarena_008.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/22/google-pixel-6a/lifestyle/-1024w2/gsmarena_016.jpg",
    ],
    desc: "Released 2022, July 21, 178g, 8.9mm thickness, Android 12, up to Android 13, 128GB storage, no card slot",
    colors: ["Charcoal"],
    price: 300,
    oldprice: 450,
    type: "offers",
    category: "mobile",
    brand: "Google",
    rating: 6.1,
  },
  {
    id: "17",
    title: "P60 Pro",
    img: "https://fdn.gsmarena.com/imgroot/reviews/23/huawei-p60-pro/lifestyle/-1024w2/gsmarena_001.jpg",
    carouselImages: [
      "https://fdn.gsmarena.com/imgroot/reviews/23/huawei-p60-pro/lifestyle/-1024w2/gsmarena_016.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/23/huawei-p60-pro/lifestyle/-1024w2/gsmarena_003.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/23/huawei-p60-pro/lifestyle/-1024w2/gsmarena_017.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/23/huawei-p60-pro/lifestyle/-1024w2/gsmarena_004.jpg",
    ],
    desc: "Released 2023, March 31, 200g, 8.3mm thickness, HarmonyOS 3.1, EMUI 13.1, 256GB/512GB storage, NM",
    colors: ["white"],
    price: 650,
    oldprice: 700,
    type: "trending",
    category: "mobile",
    brand: "Huawei ",
    rating: 6.67,
  },
  {
    id: "18",
    title: "P30 Pro",
    img: "https://fdn2.gsmarena.com/vv/pics/huawei/huawei-p30-pro-1.jpg",
    carouselImages: [
      "https://fdn.gsmarena.com/imgroot/reviews/19/huawei-p30-pro-12/gal/-1024w2/gsmarena_013.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/19/huawei-p30-pro-12/gal/-1024w2/gsmarena_014.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/19/huawei-p30-pro-12/gal/-1024w2/gsmarena_003.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/19/huawei-p30-pro-12/gal/-1024w2/gsmarena_015.jpg",
    ],
    desc: "Released 2019, March 26, 192g, 8.4mm thickness, Android 9.0, up to Android 10, EMUI 10, 128GB/256GB/512GB storage, NM",
    colors: ["Mystic Blue"],
    price: 350,
    oldprice: 386,
    type: "",
    category: "mobile",
    brand: "Huawei",
    rating: 6.47,
  },
  {
    id: "19",
    "title ": "Note20 Ultra",
    img: "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-note20-ultra-1.jpg",
    carouselImages: [
      "https://fdn.gsmarena.com/imgroot/reviews/20/samsung-galaxy-note20-ultra/review18/lifestyle/-1024w2/gsmarena_004.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/20/samsung-galaxy-note20-ultra/review18/lifestyle/-1024w2/gsmarena_003.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/20/samsung-galaxy-note20-ultra/review18/lifestyle/-1024w2/gsmarena_006.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/20/samsung-galaxy-note20-ultra/review18/lifestyle/-1024w2/gsmarena_009.jpg",
    ],
    desc: "Released 2020, August 21, 208g, 8.1mm thickness, Android 10, up to Android 13, One UI 5, 128GB/256GB/512GB storage, microSDXC",
    colors: ["Mystic Bronze"],
    price: 800,
    oldprice: 865,
    type: "trending",
    category: "mobile",
    brand: "Samsung ",
    rating: 6.9,
  },
  {
    id: "20",
    "title ": "S22 Ultra",
    img: "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s22-ultra-5g-2.jpg",
    carouselImages: [
      "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s22-ultra-5g-3.jpg",
      "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s22-ultra-5g-6.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/22/samsung-galaxy-s22-handson/lifestyle/-1024w2/gsmarena_004.jpg",
      "https://fdn.gsmarena.com/imgroot/reviews/22/samsung-galaxy-s22-handson/lifestyle/-1024w2/gsmarena_005.jpg",
    ],
    desc: "Released 2022, February 25, 228g / 229g (mmWave), 8.9mm thickness, Android 12, up to Android 13, One UI 5.1, 128GB/256GB/1TB storage, no card slot",
    colors: ["Phantom Black"],
    price: 775,
    oldprice: 850,
    type: "offers",
    category: "mobile",
    brand: "Samsung ",
    rating: 6.8,
  },
  {
    id: "21",
    title: "Fitbit Sense 2",
    img: "https://m.media-amazon.com/images/I/61c1QC4lF-L._AC_SL1500_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/61c1QC4lF-L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61Q79ulDs6L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61WpiPLatCL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61Q79ulDs6L._AC_SL1500_.jpg",
    ],
    desc: "Fitbit Sense 2 Advanced Health and Fitness Smartwatch with Tools to Manage Stress and Sleep, ECG App, SpO2, 24/7 Heart Rate and GPS, Blue Mist/Pale Gold, One Size (S & L Bands Included)",
    colors: ["White", "Gold", "Grey"],
    price: 229,
    oldprice: 299,
    type: "topseller",
    category: "Smartwatch",
    brand: "Samsung",
    rating: 4.3,
  },
  {
    id: "22",
    title: "Galaxy Watch6",
    img: "https://m.media-amazon.com/images/I/61CZSoSnVPL._AC_SL1500_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/61CZSoSnVPL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/618XT1RvyFL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61OEuoqFqYL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61oHy8hzLrL._AC_SX679_.jpg",
    ],
    desc: "SAMSUNG Galaxy Watch 6 44mm Bluetooth Smartwatch w/ Fitness Tracker, Personalized HR Zones, Advanced Sleep Coaching, Heart Monitor, BIA Sensor, Biggest Screen, US Version, Graphite",
    colors: "Graphite",
    price: 169,
    oldprice: 199,
    type: "offers",
    category: "Smartwatch",
    brand: "Samsung",
    rating: 4.4,
  },
  {
    id: "23",
    title: "Galaxy Watch5 Pro",
    img: "https://m.media-amazon.com/images/I/61Sl+xoVHoL._AC_SL1500_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/61zBT+q6ZUL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/612FGR+4kvL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61X+BMPuyjL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61e7vpK-irL._AC_SL1500_.jpg",
    ],
    desc: "SAMSUNG Galaxy Watch Pro 5 45mm LTE Smartwatch w/ Body, Health, Fitness and Sleep Tracker, Improved Battery, Sapphire Crystal Glass, GPS Route Tracking, Titanium Frame, US Version, Black",
    colors: ["Black", "", ""],
    price: 429,
    oldprice: 499,
    type: "trending",
    category: "Smartwatch",
    brand: "Samsung",
    rating: 4.5,
  },
  {
    id: "24",
    title: "Galaxy Watch 5",
    img: "https://m.media-amazon.com/images/I/61Cmk-sFNWL._AC_SL1500_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/61Cmk-sFNWL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61a4IxWPY+L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61X2Pl7752L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61z3Su8F2jL._AC_SL1500_.jpg",
    ],
    desc: "SAMSUNG Galaxy Watch 5 40mm Bluetooth Smartwatch w/ Body, Health, Fitness and Sleep Tracker, Improved Battery, Sapphire Crystal Glass, Enhanced GPS Tracking, US Version, Pink Gold Bezel w/ Pink Band",
    colors: ["Pink", "Black", "Gray", "Navy/ Mustard"],
    type: "trending",
    price: 199,
    oldprice: 279,
    category: "Smartwatch",
    brand: "Samsung",
    rating: 4.6,
  },
  {
    id: "25",
    title: "Watch 4 Classic",
    img: "https://m.media-amazon.com/images/I/61em2RBifsL._AC_SL1500_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/61em2RBifsL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61dh16sj5+L._AC_SL1356_.jpg",
      "https://m.media-amazon.com/images/I/61IZmXci7qS._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61StAtbybxL._AC_SL1500_.jpg",
    ],
    desc: "SAMSUNG Galaxy Watch 4 Classic 46mm Smartwatch with ECG Monitor Tracker for Health, Fitness, Running, Sleep Cycles, GPS Fall Detection, Bluetooth, US Version, Silver",
    colors: ["Silver", "Black", "Gold"],
    price: 169,
    oldprice: 199,
    type: "trending",
    category: "Smartwatch",
    brand: "Samsung",
    rating: 4.6,
  },
  {
    id: "26",
    title: "Apple Watch Ultra",
    img: "https://m.media-amazon.com/images/I/916acEhBkcL._AC_SL1500_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/916acEhBkcL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/91z5KuonXrL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/91v9yAPw3-L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/91jzT-Hi-TL._AC_SL1500_.jpg",
    ],
    desc: "Apple Watch Ultra [GPS + Cellular 49mm] Smart Watch w/Rugged Titanium Case & Green Alpine Loop Small. Fitness Tracker, Precision GPS, Action Button, Extra-Long Battery Life, Brighter Retina Display",
    colors: ["Green", "Orange", "White"],
    price: 900,
    oldprice: 994,
    type: "",
    category: "Smartwatch",
    brand: "Apple",
    rating: 4.7,
  },
  {
    id: "27",
    title: "Apple Watch 8",
    img: "https://m.media-amazon.com/images/I/71uOgDy40BL._AC_SL1500_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/71uOgDy40BL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71k5hLGKeeL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71ulah9iIwL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/714rxoYlmsL._AC_SL1500_.jpg",
    ],
    desc: "Apple Watch Series 8 [GPS 41mm] Smart Watch w/Starlight Aluminum Case with Starlight Sport Band - S/M. Fitness Tracker, Blood Oxygen & ECG Apps, Always-On Retina Display, Water Resistant",
    colors: ["Starlight", "red", "Black", "White"],
    price: 875,
    oldprice: 899,
    type: "trending",
    category: "Smartwatch",
    brand: "Apple",
    rating: 4.7,
  },
  {
    id: "28",
    title: "Apple Watch SE",
    img: "https://m.media-amazon.com/images/I/71LfnkRgZ4L._AC_SL1500_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/71LfnkRgZ4L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61ripYHNMfL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/716tEwpUImL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/91GkjaDhHoL._AC_SL1500_.jpg",
    ],
    desc: "Apple Watch SE (2nd Gen) [GPS 40mm] Smart Watch w/Midnight Aluminum Case & Midnight Sport Band - S/M. Fitness & Sleep Tracker, Crash Detection, Heart Rate Monitor, Retina Display, Water Resistant",
    colors: ["Black", "silver", "Starlight"],
    price: 269,
    oldprice: 280,
    type: "offers",
    category: "Smartwatch",
    brand: "Apple",
    rating: 4.7,
  },
  {
    id: "29",
    title: "Redmi Watch 3",
    img: "https://m.media-amazon.com/images/I/51gVoKZTDsL._AC_SL1500_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/61m73yeO26L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/614-NeV3TZL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51gVoKZTDsL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61kBMjxkuFL._AC_SL1500_.jpg",
    ],
    desc: "Xiaomi Redmi Watch 3 Smart Watch with Alexa Built-in for Men Women, GPS Fitness Tracker with 120+ Sport Modes, Blood Oxygen Heart Rate Sleep Monitor,Bluetooth Phone Call Watch for iPhone Android",
    colors: ["Black", "White"],
    price: 110,
    oldprice: 120,
    type: "trending",
    category: "Smartwatch",
    brand: "Xiaomi",
    rating: 4,
  },
  {
    id: "30",
    title: "Redmi Watch 2 Lite",
    img: "https://m.media-amazon.com/images/I/51MprLPx6YL._AC_SL1200_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/51MprLPx6YL._AC_SL1200_.jpg",
      "https://m.media-amazon.com/images/I/51zmgCozZcL._AC_SL1200_.jpg",
      "https://m.media-amazon.com/images/I/61yfsk1TcHL._AC_UX569_.jpg",
      "https://m.media-amazon.com/images/I/51d8+shnv9L._AC_SL1200_.jpg",
    ],
    desc: "Xiaomi Redmi Watch 2 Lite, 100+ Fitness Modes, 1.55 colorsful Touch Display, 5 ATM Water Resistance, SPO₂ Measurement, 24-Hour Heart Rate Tracking, Multi-System Standalone GPS, Black",
    colors: ["Black", "Green"],
    price: 59,
    oldprice: 69,
    type: "trending",
    category: "Smartwatch",
    brand: "Xiaomi",
    rating: 4.3,
  },
  {
    id: "31",
    title: "HP Notebook Laptop",
    img: "https://m.media-amazon.com/images/I/61oAh3XrX+L._AC_SL1500_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/61TRshMKRHL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61QY5j4niXL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51hOj37A-PL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61WCPgA347L._AC_SL1500_.jpg",
    ],
    desc: "HP Notebook Laptop, 15.6 HD Touchscreen, Intel Core i3-1115G4 Processor, 32GB RAM, 1TB PCIe SSD, Webcam, Type-C, HDMI, SD Card Reader, Wi-Fi, Windows 11 Home, Silver",
    colors: ["Silver"],
    price: 481,
    oldprice: 699,
    type: "topseller",
    category: "Laptop",
    brand: "HP",
    rating: 4.4,
  },
  {
    id: "32",
    title: "HP Notebook Laptop",
    img: "https://m.media-amazon.com/images/I/715luCK53hL._AC_SL1500_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/617VcZLs1xL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51Byngq5QES._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71VriE-x0xL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61H4xuL3wlS._AC_SL1500_.jpg",
    ],
    desc: "acer 2023 Newest Aspire 5 15.6 FHD IPS Slim Laptop, Intel Core i3-1115G4(Up to 4.1GHz), 20GB RAM, 512GB NVMe SSD, WiFi 6, USB, RJ-45, Webcam, Amazon Alexa, Windows 11 S, w/GM Accessory",
    colors: ["Silver"],
    price: 499.99,
    oldprice: 625,
    type: "offer",
    category: "Laptop",
    brand: "Acer",
    rating: 4.4,
  },
  {
    id: "33",
    title: "Lenovo IdeaPad 3",
    img: "https://m.media-amazon.com/images/I/71k1fRLrvnL._AC_SL1400_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/61wS2fFgIsL._AC_SL1397_.jpg",
      "https://m.media-amazon.com/images/I/611QESrGnhL._AC_SL1277_.jpg",
      "https://m.media-amazon.com/images/I/41a3z7vWZiL._AC_SL1355_.jpg",
      "https://m.media-amazon.com/images/I/416aJuoVy9L._AC_SL1315_.jpg",
    ],
    desc: "Lenovo IdeaPad 3 14 FHD Slim Laptop, Intel Core i7-1165G7(Up to 4.70GHz), 20GB RAM, 512GB NVMe SSD, Fingerprint Reader, WiFi 6, Webcam, Type-A&C, HDMI, CUE Accessories, Windows 11",
    colors: ["Black"],
    price: 629,
    oldprice: 699,
    type: "",
    category: "Laptop",
    brand: "Lenovo",
    rating: 4.6,
  },
  {
    id: "34",
    title: "IdeaPad Gaming 3",
    img: "https://m.media-amazon.com/images/I/81zcUyiNcUL._AC_SL1500_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/81+9W1bYZyL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71HqnI+6wTL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/714756vspeL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61S6+275UxL._AC_SL1500_.jpg",
    ],
    desc: "Lenovo IdeaPad Gaming 3 - (2022) - Essential Gaming Laptop Computer - 15.6 FHD - 120Hz - AMD Ryzen 5 6600H - NVIDIA GeForce RTX 3050 - 8GB DDR5 RAM - 256GB NVMe Storage - Windows 11 Home",
    colors: ["Black"],
    price: 659.99,
    oldprice: 899.99,
    type: "trending",
    category: "Laptop",
    brand: "Lenovo",
    rating: 4.3,
  },
  {
    id: "35",
    title: "IdeaPad Gaming 3",
    img: "https://m.media-amazon.com/images/I/61oicHA-qcL._AC_SL1500_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/71FxdxK5rNL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61Ny61BxF9L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51VcHP29PVL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71y2Jcl3uSL._AC_SL1500_.jpg",
    ],
    desc: "ASUS Vivobook 15.6 FHD Laptop, 6-core Intel Core i3-1215U(up to 4.4GHz), 16GB RAM, 1TB PCIE SSD, HDMI, Webcam, USB-A&C, Windows 11+ GM Accessory",
    colors: ["Navy"],
    price: 489.99,
    oldprice: 500,
    type: "trending",
    category: "Laptop",
    brand: "ASUS",
    rating: 4.3,
  },
  {
    id: "36",
    title: "ASUS Vivobook",
    img: "https://m.media-amazon.com/images/I/71iNyraKfPL._AC_SL1500_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/710DKWU3y5L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71kv8lsEVpL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71YHRNh+ycL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61N+yhM5j-L._AC_SL1500_.jpg",
    ],
    desc: "ASUS Vivobook 15.6 FHD Laptop, 6-core Intel Core i3-1215U(up to 4.4GHz), 16GB RAM, 1TB PCIE SSD, HDMI, Webcam, USB-A&C, Windows 11+ GM Accessory",
    colors: ["Navy"],
    price: 489.99,
    oldprice: 579,
    type: "trending",
    category: "Laptop",
    brand: "ASUS",
    rating: 4.4,
  },
  {
    id: "37",
    title: "LG gram Style",
    img: "https://m.media-amazon.com/images/I/71zAKORB6hL._AC_SL1500_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/715rESc4auL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/615QCTc5G5L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61ULBQC-n5L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51wN9CG0qZL._AC_SL1500_.jpg",
    ],
    desc: "LG gram Style 16 OLED Laptop, Intel 13th Gen Core i7 Evo Platform, Windows 11 Home, 32GB RAM, 1TB SSD, Dynamic White",
    colors: ["White"],
    price: 1696,
    oldprice: 1999,
    type: "offers",
    category: "Laptop",
    brand: "LG",
    rating: 4,
  },
  {
    id: "38",
    title: "LG gram 2in1",
    img: "https://m.media-amazon.com/images/I/81D9knGjZ5L._AC_SL1500_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/717pottSkKL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81W9pQwXRfL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81ajBOnlu0L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81C0a3UcA-L._AC_SL1500_.jpg",
    ],
    desc: "LG gram 16 2in1 Lightweight Laptop, Intel 13th Gen Core i7 Evo Platform, Windows 11 Home, 16GB RAM, 512GB SSD, Black",
    colors: ["Black"],
    price: 999,
    oldprice: 1599,
    type: "topseller",
    category: "Laptop",
    brand: "LG",
    rating: 4,
  },
  {
    id: "39",
    title: "SAMSUNG 14 Galaxy",
    img: "https://m.media-amazon.com/images/I/519KZO0oXaL._AC_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/41FMqyAOuSL._AC_.jpg",
      "https://m.media-amazon.com/images/I/41z-zMTj59L._AC_.jpg",
      "https://m.media-amazon.com/images/I/31ZXTQkNscL._AC_.jpg",
      "https://m.media-amazon.com/images/I/21lQRriqMVL._AC_.jpg",
    ],
    desc: "SAMSUNG 14 Galaxy Book2 Business Laptop Computer, i7-1260P / 32GB /512GB, Windows 11 PRO, 12th Gen Intel vPro 28W Processor w/ Enhanced Security, ‎NP641BED-KA3US, Graphite",
    colors: ["Graphite"],
    price: 1189,
    oldprice: 1300,
    type: "trending",
    category: "Laptop",
    brand: "SAMSUNG",
    rating: 4,
  },
  {
    id: "40",
    title: "LG gram 2in1",
    img: "https://m.media-amazon.com/images/I/81D9knGjZ5L._AC_SL1500_.jpg",
    carouselImages: [
      "https://m.media-amazon.com/images/I/717pottSkKL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81W9pQwXRfL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81ajBOnlu0L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81C0a3UcA-L._AC_SL1500_.jpg",
    ],
    desc: "Microsoft Surface Laptop 4 13.5” Touch-Screen – Intel Core i7 - 16GB - 512GB Solid State Drive - Matte Black",
    colors: ["Matte Black", "Sandstone", "Ice Blue", "Platinum"],
    price: 999,
    oldprice: 1699,
    type: "Trending",
    category: "Laptop",
    brand: "Microsoft",
    rating: 4.6,
  },

  {
    id: "41",
    title: "iPad Pro 12.9",
    img: "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-pro-129-2022-1.jpg",
    carouselImages: [
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-pro-129-2022-2.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-pro-2022.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-pro-129-2022-1.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-pro-129-2022-2.jpg",
    ],
    desc: "Also known as Apple iPad Pro (12.9-inch, 6th generation) Wi-Fi + Cellular & GPS: A2764, A2437 (Global); A2766 (China) Wi-Fi only, w/o GPS: A2436",
    colors: ["Silver", "Space Gray"],
    price: 1200,
    oldprice: 1450,
    type: "trending",
    category: "tablets",
    brand: "Apple",
    rating: 4.4,
  },
  {
    id: "42",
    title: "Apple iPad",
    img: "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-10-2022-0.jpg",
    carouselImages: [
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-10-2022-1.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-10-2022-2.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-10-2022-0.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-10-2022-1.jpg",
    ],
    desc: "Also known as Apple iPad Pro (12.9-inch, 6th generation) Wi-Fi + Cellular & GPS: A2764, A2437 (Global); A2766 (China) Wi-Fi only, w/o GPS: A2436",
    colors: ["Silver", "Blue", "Pink", "Yellow"],
    price: 540,
    oldprice: 580,
    type: "topseller",
    category: "tablets",
    brand: "Apple",
    rating: 4.4,
  },
  {
    id: "43",
    title: "iPad 10.2",
    img: "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad8-102-inches-2020-01.jpg",
    carouselImages: [
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad8-102-inches-2020-2.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad8-102-inches-2020-3.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad8-102-inches-2020-4.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad8-102-inches-2020-01.jpg",
    ],
    desc: "Also known as Apple iPad 9th Gen, Apple iPad (9th generation) Versions: A2603, A2604 (Global)",
    colors: ["Silver", "Space", "Gray"],
    price: 400,
    oldprice: 430,
    type: "offers",
    category: "tablets",
    brand: "Apple",
    rating: 4.4,
  },
  {
    id: "44",
    title: "iPad 10.2",
    img: "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-102-2021-1.jpg",
    carouselImages: [
      "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-102-2021-.jpg",
      "https://www.dna.jo/cdn/shop/products/iPad_10.2_inch_Wi-Fi_Space_Gray_PDP_Image_Position-2_EN_819x819.jpg?v=1634027357",
      "https://www.dna.jo/cdn/shop/products/iPad_10.2_inch_Wi-Fi_Space_Gray_PDP_Image_Position-8_EN_819x819.jpg?v=1634027357",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-102-2021-1.jpg",
    ],
    desc: "Also known as Apple iPad 9th Gen, Apple iPad (9th generation) Versions: A2603, A2604 (Global)",
    colors: ["Silver", "Space", "Gray"],
    price: 400,
    oldprice: 430,
    type: "trending",
    category: "tablets",
    brand: "Apple",
    rating: 4.4,
  },
  {
    id: "45",
    title: "iPad Air",
    img: "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-air4-2020-01.jpg",
    carouselImages: [
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-air4-2020-2.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-air4-2020-3.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-air4-2020-4.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-air4-2020-5.jpg",
    ],
    desc: "Also known as Apple iPad Air 4, iPad Air (4th generation) Wi-Fi + Cellular & GPS: A2324, A2072 (Global), A2325 (China)  Wi-Fi only, w/o GPS: A2316",
    colors: ["Space Gray", "Silver", "Rose Gold", "Green, Sky Blue"],
    price: 600,
    oldprice: 640,
    type: "Trending",
    category: "tablets",
    brand: "Apple",
    rating: 4.4,
  },
  {
    id: "46",
    title: "iPad Pro 12.9",
    img: "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-pro-129-2021-1.jpg",
    carouselImages: [
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-pro-129-2021-2.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-pro-129-2021-1.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-pro-129-2021-2.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-pro-129-2021-1.jpg",
    ],
    desc: "Also known as Apple iPad Pro (12.9-inch, 5th generation) Wi-Fi + Cellular & GPS: A2379, A2461 (Global); A2462 (China)",
    colors: ["Silver", "Space Gray"],
    price: 1000,
    oldprice: 1200,
    type: "offers",
    category: "tablets",
    brand: "Apple",
    rating: 4.4,
  },
  {
    id: "47",
    title: "iPad Pro 11 ",
    img: "https://fdn2.gsmarena.com/vv/bigpic/apple-ipad-pro-11-2020.jpg",
    carouselImages: [
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-pro-2020-1.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-pro-2020-2.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-pro-2020-1.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-pro-2020-2.jpg",
    ],
    desc: "Also known as Apple iPad Pro (11-inch, 2nd generation)Wi-Fi + Cellular & GPS: A2068, A2230 (Global), A2231 (China) Wi-Fi only, w/o GPS: A2228 (Global)",
    colors: ["Silver", "Space Gray"],
    price: 750,
    oldprice: 800,
    type: "",
    category: "tablets",
    brand: "Apple",
    rating: 4.4,
  },
  {
    id: "48",
    title: "iPad 10.2",
    img: "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad7-1.jpg",
    carouselImages: [
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad7-2.jpg",
      "https://m.media-amazon.com/images/I/610zP9GVbsL.jpg",
      "https://m.media-amazon.com/images/I/51nc1B2I3sL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51h5xAeHJHL._AC_SL1500_.jpg",
    ],
    desc: "Also known as Apple iPad 7th Gen, Apple iPad (7th generation)Wi-Fi + Cellular & GPS: A2200, A2198 (Globa) Wi-Fi only, w/o GPS: A2197 (Global)",
    colors: ["Silver", "Space Gray", "Gold"],
    price: 300,
    oldprice: 350,
    type: "trending",
    category: "tablets",
    brand: "Apple",
    rating: 4.4,
  },
  {
    id: "49",
    title: "iPad mini 4",
    img: "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-mini-4-1.jpg",
    carouselImages: [
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-mini-4-0.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-mini-4-0.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-mini-4-2.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-mini-4-3.jpg",
    ],
    desc: "Also known as Apple iPad mini with Retina display",
    colors: ["Silver", "Space Gray", "Gold"],
    price: 300,
    oldprice: 360,
    type: "Trending",
    category: "tablets",
    brand: "Apple",
    rating: 4.4,
  },
  {
    id: "50",
    title: "iPad 9.7 ",
    img: "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-97-2017-1.jpg",
    carouselImages: [
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-97-2017-2.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-97-2017-3.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-97-2017-1.jpg",
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-97-2017-2.jpg",
    ],
    desc: "Also known as Apple iPad (5th generation)Wi-Fi + Cellular & GPS: A1823 (Global) Wi-Fi only, w/o GPS: A1822 (Global)",
    colors: ["Silver", "Space Gray"],
    price: 350,
    oldprice: 390,
    type: "",
    category: "tablets",
    brand: "Apple",
    rating: 4.4,
  },
];

const bestSeller = "https://static.vecteezy.com/system/resources/previews/010/251/736/original/best-seller-red-ribbon-illustration-free-png.png"

module.exports = {
  productsList,
  bestSeller
};
